# -*- coding: utf-8 -*-
"""FAQs ChatBot .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJUud2OTWIuAZXw10lS6YMKDaDrl7_vC

# Internship: CodeAlpha
# Task: 01- FAQs ChatBot
# Developer Name: Tauseef Alam

#

# Step 1: Install Dependencies
"""

!pip install -q deep-translator langdetect gradio

"""# Step 2: The Core Application"""

import gradio as gr
from deep_translator import GoogleTranslator
from langdetect import detect, LangDetectException

# ── 1. Language Definitions ──────────────────────────────────────────────────
LANGUAGES = {
    "Auto Detect": "auto", "English": "en", "Urdu": "ur", "Arabic": "ar",
    "Hindi": "hi", "French": "fr", "Spanish": "es", "German": "de",
    "Chinese (Simplified)": "zh-CN", "Japanese": "ja", "Russian": "ru",
    "Portuguese": "pt", "Italian": "it", "Korean": "ko", "Turkish": "tr",
    "Dutch": "nl", "Polish": "pl", "Bengali": "bn", "Persian (Farsi)": "fa",
    "Punjabi": "pa", "Pashto": "ps", "Swahili": "sw", "Indonesian": "id",
}
lang_names = list(LANGUAGES.keys())

# ── 2. Core Functions ────────────────────────────────────────────────────────
def detect_language(text):
    try:
        if not text or len(text.strip()) < 3:
            return "en"
        return detect(text)
    except LangDetectException:
        return "en"

def translate_text(text, source_lang_name, target_lang_name):
    if not text or not text.strip():
        return "⚠️ Please initiate translation with valid text."

    if len(text) > 5000:
        return "⚠️ Text exceeds the 5000 character system limit."

    source_code = LANGUAGES[source_lang_name]
    target_code = LANGUAGES[target_lang_name]

    if source_code == target_code and source_code != "auto":
        return "⚠️ Source and target languages are identical."

    if source_code == "auto":
        source_code = detect_language(text)

    try:
        translator = GoogleTranslator(source=source_code, target=target_code)
        translated = translator.translate(text)
        return translated if translated else "❌ Translation returned empty."
    except Exception as error:
        return f"❌ Translation failure: {str(error)}"

def update_char_count(text):
    count = len(text) if text else 0
    return f"{count} / 5000 characters"

def swap_languages(src, tgt, translated_text):
    new_src = tgt
    new_tgt = src if src != "Auto Detect" else "English"
    return new_src, new_tgt, translated_text, ""

def clear_all():
    return "", "", "0 / 5000 characters"

# ── 3. Custom UI Theme ───────────────────────────────────────────────────────
# Designing a sleek, high-tech interface
custom_theme = gr.themes.Base(
    font=[gr.themes.GoogleFont("Roboto Mono"), "monospace", "sans-serif"]
).set(
    body_background_fill="#0A192F",          # Deep Navy
    block_background_fill="#112240",         # Lighter Navy for panels
    block_border_color="#64FFDA",            # Cyan borders
    block_label_text_color="#64FFDA",        # Cyan labels
    body_text_color="#E6F1FF",               # Light text for readability
    button_primary_background_fill="#FF6B00",# Orange Action Buttons
    button_primary_text_color="#FFFFFF",
    button_primary_border_color="#FF6B00",
    button_secondary_background_fill="transparent",
    button_secondary_text_color="#64FFDA",
    button_secondary_border_color="#64FFDA",
    input_background_fill="#0A192F",
    color_accent_soft="#112240"
)

# ── 4. Build the Gradio Application ──────────────────────────────────────────
def build_app():
    with gr.Blocks(title="Neural Translation Engine", theme=custom_theme) as demo:
        gr.Markdown("""
        # 🌐 Neural Translation Engine
        **CodeAlpha AI Internship — Task 1**
        """)

        with gr.Row():
            # Source Column
            with gr.Column(scale=1):
                source_lang = gr.Dropdown(choices=lang_names, value="Auto Detect", label="📥 Source Language", interactive=True)
                input_text = gr.Textbox(lines=8, placeholder="Initialize text sequence here...", label="Input Text")
                char_count = gr.Textbox(value="0 / 5000 characters", label="", interactive=False)

            # Controls Column
            with gr.Column(scale=0, min_width=60):
                gr.Markdown("<br><br><br>")
                swap_btn = gr.Button("⇄", variant="secondary")

            # Target Column
            with gr.Column(scale=1):
                target_lang = gr.Dropdown(choices=lang_names, value="Urdu", label="📤 Target Language", interactive=True)
                output_text = gr.Textbox(lines=8, label="Translated Output", interactive=False, show_copy_button=True)

        # Action Buttons
        with gr.Row():
            translate_btn = gr.Button("🔄 Execute Translation", variant="primary", scale=3)
            clear_btn = gr.Button("🗑️ Clear Interface", variant="secondary", scale=1)

        # Wiring Events
        translate_btn.click(fn=translate_text, inputs=[input_text, source_lang, target_lang], outputs=output_text)
        input_text.submit(fn=translate_text, inputs=[input_text, source_lang, target_lang], outputs=output_text)
        input_text.change(fn=update_char_count, inputs=input_text, outputs=char_count)
        swap_btn.click(fn=swap_languages, inputs=[source_lang, target_lang, output_text], outputs=[source_lang, target_lang, input_text, output_text])
        clear_btn.click(fn=clear_all, outputs=[input_text, output_text, char_count])

    return demo

# ── 5. Launch Protocol ───────────────────────────────────────────────────────
if __name__ == "__main__":
    app = build_app()
    app.launch(share=True, debug=True)